### ISSUE TITLE
while vs for

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/oop#10]
https://github.com/fisheye36/oop/blob/820743ca10dc3960affd0374fa7a5a45ae3e9f1c/lab-02/Czary.cpp#L65

Ten kod wygląda dobrze, tylko "głośno" zastanawiam się czy w tym miejscu pętla `for` wyglądałaby lepiej czy nie.
```
int rozmiar = 0;
for (KsiegaCzarow ksiegaTymczasowa = ksiega; ksiegaTymczasowa != 0; ksiegaTymczasowa = ksiegaTymczasowa->nastepna)
		rozmiar++;
```

**Comment by fisheye36** [comment]
W pętli `for` jest to faktycznie bardziej czytelne i zwięzłe.
