### ISSUE TITLE
rozmiar++ i ++rozmiar

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/oop#11]
https://github.com/fisheye36/oop/blob/820743ca10dc3960affd0374fa7a5a45ae3e9f1c/lab-02/Czary.cpp#L67

Ewentualnie można by zamienić postinkrementację na preinkrementację, aby nie robić dodatkowej kopii liczby, chociaż w przypadku zmiennych wbudowanych nie ma to większego znaczenia.

**Comment by fisheye36** [comment]
Z tego co kiedyś czytałem w przypadku wyrażenia zawierającego jedynie inkrementację jednej zmiennej (jak tutaj `rozmiar++` czy w pętli `for` `i++`) nie ma to absolutnie żadnego znaczenia. Kompilator i tak zamieni to na preinkrementację, ponieważ widzi, że ta operacja nie jest częścią większego wyrażenia i nie wpłynie to w żadnym wypadku na zmianę zachowania programu. Aby się upewnić utworzyłem kopię pliku Czary.cpp, gdzie każdą postinkrementację zamieniłem na preinkrementację, wykonałem komendę `g++ -S nazwa_pliku.cpp` a potem sprawdziłem różnicę - nie było żadnej. Być może lata temu miało to znaczenie ale dzisiejsze kompilatory raczej wykonują taką prostą optymalizację na porządku dziennym (nawet bez dodatkowych opcji kompilacji).

**Comment by GrzegorzGach** [comment]
Tak, zmienne wbudowane zwykle są dobrze zoptymalizowane natomiast dla obiektów widać różnice.
