### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/oop#12]
https://github.com/fisheye36/oop/blob/820743ca10dc3960affd0374fa7a5a45ae3e9f1c/lab-02/Czary.cpp#L86

Należy uważać na `NULL`, ponieważ to nie jest słowo kluczowe ze standardu tylko `#define` w bibliotece standardowej, więc jeżeli nie ma dołączonego żadnego pliku z biblioteki to ten symbol nie istnieje. W podstawowym C++, w takiej sytuacji trzeba używać zwykłego `0`. W nowym standardzie pojawia się `nullptr`, który służy właśnie do oznaczania wskaźników nie wskazujących na nic.

**Comment by fisheye36** [comment]
Niby tak ale kompilator wyświetliłby błąd, jeżeli nie znalazłby definicji makra `NULL`. Dla bezpieczeństwa jednak zamieniłem wszystkie wystąpienia `NULL` na `0`.
