### ISSUE TITLE
Czy warto using?

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/oop#7]
https://github.com/fisheye36/oop/blob/820743ca10dc3960affd0374fa7a5a45ae3e9f1c/lab-02/Czary.cpp#L16

W tej funkcji ma Pan tylko jedno wystąpienie `cout`. Chyba wygodniej byłoby po prostu napisać `std::cout`. Ewentualnie można wewnątrz funkcji dać `using namespace std;`, ponieważ używa Pan `cout` i `endl`.

**Comment by fisheye36** [comment]
Mam 2 wystąpienia `cout` (w pętli i poza nią) - dlatego też użyłem `using std::cout;`. Co do `using namespace std;` to staram się tego nigdzie nie używać, gdyż jest to zła praktyka programistyczna (co prawda w takim programie nie ma to praktycznie żadnego znaczenia ale chodzi o samą zasadę).

**Comment by GrzegorzGach** [comment]
Nie powiedziałbym, że `using namespace std;` jest złe. To zależy jak się go używa. Jeżeli używa się go np. wewnątrz funkcji, to absolutnie nie ma z nim problemu. Jeżeli w całym pliku .cpp to rzeczywiście lepiej z tym uważać. Oczywiście, w plikach nagłówkowych jest to niedopuszczalne.
